#!/bin/bash
# Render alertmanager.yml and the Caddy gateway config from the environment, then run
# Alertmanager (private, reachable by Prometheus) behind Caddy (public, basic auth).
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*" >&2; }
die() { printf '[entrypoint] FATAL: %s\n' "$*" >&2; exit 1; }

PORT="${PORT:-8080}"
ALERTMANAGER_PORT="${ALERTMANAGER_PORT:-9093}"
AUTH_USERNAME="${AUTH_USERNAME:-admin}"
AUTH_PASSWORD="${AUTH_PASSWORD:-}"
EXTERNAL_URL="${EXTERNAL_URL:-}"
GROUP_BY="${GROUP_BY:-alertname,job}"
GROUP_WAIT="${GROUP_WAIT:-30s}"
GROUP_INTERVAL="${GROUP_INTERVAL:-5m}"
REPEAT_INTERVAL="${REPEAT_INTERVAL:-4h}"
RESOLVE_TIMEOUT="${RESOLVE_TIMEOUT:-5m}"
SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL:-}"
SLACK_CHANNEL="${SLACK_CHANNEL:-#alerts}"
WEBHOOK_URL="${WEBHOOK_URL:-}"
ALERT_EMAIL_TO="${ALERT_EMAIL_TO:-}"
SMTP_SMARTHOST="${SMTP_SMARTHOST:-}"
SMTP_FROM="${SMTP_FROM:-alertmanager@localhost}"
SMTP_USERNAME="${SMTP_USERNAME:-}"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"
SMTP_REQUIRE_TLS="${SMTP_REQUIRE_TLS:-true}"
DATA_DIR="${DATA_DIR:-${RAILWAY_VOLUME_MOUNT_PATH:-/alertmanager}/data}"

case "$EXTERNAL_URL" in ""|"https://"|"http://") EXTERNAL_URL="" ;; esac

[ -n "$AUTH_PASSWORD" ] || die "AUTH_PASSWORD is unset. Alertmanager has no built-in authentication, so the gateway refuses to publish an open instance."

# "a, b ,c" -> [a, b, c]
yaml_bare_list() {
  local raw="$1" item out=""
  local IFS=','
  for item in $raw; do
    item="$(printf '%s' "$item" | tr -d '[:space:]')"
    [ -n "$item" ] || continue
    [ -z "$out" ] || out="$out, "
    out="$out$item"
  done
  printf '[%s]' "$out"
}

render_alertmanager_yml() {
  cat <<EOF
# Generated by entrypoint.sh on every boot. Edit the environment, not this file.
global:
  resolve_timeout: ${RESOLVE_TIMEOUT}
EOF

  if [ -n "$SMTP_SMARTHOST" ]; then
    cat <<EOF
  smtp_smarthost: "${SMTP_SMARTHOST}"
  smtp_from: "${SMTP_FROM}"
  smtp_require_tls: ${SMTP_REQUIRE_TLS}
EOF
    if [ -n "$SMTP_USERNAME" ]; then
      cat <<EOF
  smtp_auth_username: "${SMTP_USERNAME}"
  smtp_auth_password: "${SMTP_PASSWORD}"
EOF
    fi
  fi

  cat <<EOF

route:
  receiver: default
  group_by: $(yaml_bare_list "$GROUP_BY")
  group_wait: ${GROUP_WAIT}
  group_interval: ${GROUP_INTERVAL}
  repeat_interval: ${REPEAT_INTERVAL}

receivers:
  - name: default
EOF

  if [ -n "$SLACK_WEBHOOK_URL" ]; then
    cat <<EOF
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "${SLACK_CHANNEL}"
        send_resolved: true
        title: "{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}\\n{{ end }}"
EOF
  fi

  if [ -n "$WEBHOOK_URL" ]; then
    cat <<EOF
    webhook_configs:
      - url: "${WEBHOOK_URL}"
        send_resolved: true
EOF
  fi

  if [ -n "$ALERT_EMAIL_TO" ] && [ -n "$SMTP_SMARTHOST" ]; then
    cat <<EOF
    email_configs:
      - to: "${ALERT_EMAIL_TO}"
        send_resolved: true
EOF
  fi

  cat <<EOF

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, job, instance]
EOF
}

render_caddyfile() {
  local hash="$1"
  cat <<EOF
{
	admin off
	auto_https off
	servers {
		trusted_proxies static 100.64.0.0/10 fd00::/8 152.233.0.0/17
	}
}

:${PORT} {
	# Anonymous, so Railway's health prober reaches it, and a real dependency check:
	# it is Alertmanager's own readiness endpoint, not a static 200 from the gateway.
	handle /healthz {
		rewrite * /-/ready
		reverse_proxy 127.0.0.1:${ALERTMANAGER_PORT}
	}

	handle {
		basic_auth {
			${AUTH_USERNAME} ${hash}
		}
		reverse_proxy 127.0.0.1:${ALERTMANAGER_PORT}
	}
}
EOF
}

if [ -n "$SLACK_WEBHOOK_URL" ]; then log "notifications: slack"; fi
if [ -n "$WEBHOOK_URL" ]; then log "notifications: webhook"; fi
if [ -n "$ALERT_EMAIL_TO" ] && [ -n "$SMTP_SMARTHOST" ]; then log "notifications: email"; fi
if [ -z "$SLACK_WEBHOOK_URL$WEBHOOK_URL$SMTP_SMARTHOST" ]; then
  log "notifications: none configured - alerts are visible in the Alertmanager UI only"
fi
log "external url: ${EXTERNAL_URL:-<none>}"

render_alertmanager_yml > /etc/alertmanager/alertmanager.yml
AUTH_HASH="$(caddy hash-password --plaintext "$AUTH_PASSWORD")"
[ -n "$AUTH_HASH" ] || die "caddy hash-password produced an empty hash"
render_caddyfile "$AUTH_HASH" > /etc/caddy/Caddyfile

/bin/amtool check-config /etc/alertmanager/alertmanager.yml
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile

mkdir -p "$DATA_DIR"
chown -R alertmanager:alertmanager "$DATA_DIR" /etc/alertmanager /etc/caddy /var/lib/caddy
chown alertmanager:alertmanager "$(dirname "$DATA_DIR")" 2>/dev/null || true

AM_ARGS=(
  --config.file=/etc/alertmanager/alertmanager.yml
  --storage.path="$DATA_DIR"
  --web.listen-address="[::]:${ALERTMANAGER_PORT}"
  # Single replica: without this Alertmanager opens a gossip listener nothing joins.
  --cluster.listen-address=
)
[ -z "$EXTERNAL_URL" ] || AM_ARGS+=(--web.external-url="$EXTERNAL_URL")

su-exec alertmanager:alertmanager /bin/alertmanager "${AM_ARGS[@]}" &
AM_PID=$!
su-exec alertmanager:alertmanager caddy run --config /etc/caddy/Caddyfile --adapter caddyfile &
CADDY_PID=$!

shutdown() { kill -TERM "$AM_PID" "$CADDY_PID" 2>/dev/null || true; }
trap shutdown TERM INT

# Either process exiting must take the container down, or a dead Alertmanager hides
# behind a live gateway until an alert silently fails to deliver.
wait -n || true
log "a supervised process exited; shutting down"
shutdown
wait || true
exit 1
