#!/bin/bash
# Render prometheus.yml and the Caddy gateway config from the environment, then run
# Prometheus (private, on the Railway private network) behind Caddy (public, basic auth).
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*"; }
die() { printf '[entrypoint] FATAL: %s\n' "$*" >&2; exit 1; }

PORT="${PORT:-8080}"
PROMETHEUS_PORT="${PROMETHEUS_PORT:-9090}"
AUTH_USERNAME="${AUTH_USERNAME:-admin}"
AUTH_PASSWORD="${AUTH_PASSWORD:-}"
SCRAPE_INTERVAL="${SCRAPE_INTERVAL:-15s}"
SCRAPE_TIMEOUT="${SCRAPE_TIMEOUT:-10s}"
RETENTION_TIME="${RETENTION_TIME:-15d}"
RETENTION_SIZE="${RETENTION_SIZE:-4GB}"
METRICS_PATH="${METRICS_PATH:-/metrics}"
SCRAPE_TARGETS="${SCRAPE_TARGETS:-}"
PROBE_TARGETS="${PROBE_TARGETS:-}"
PROBE_MODULE="${PROBE_MODULE:-http_2xx}"
ALERTMANAGER_HOST="${ALERTMANAGER_HOST:-}"
BLACKBOX_HOST="${BLACKBOX_HOST:-}"
EXTERNAL_URL="${EXTERNAL_URL:-}"
DATA_DIR="${DATA_DIR:-${RAILWAY_VOLUME_MOUNT_PATH:-/prometheus}/data}"

# A ${{svc.RAILWAY_PRIVATE_DOMAIN}} reference renders empty until that service owns a
# deployment, which is exactly the state a template's first deploy is in. Repair on shape.
case "$ALERTMANAGER_HOST" in ""|:*) ALERTMANAGER_HOST="alertmanager.railway.internal:9093" ;; esac
case "$BLACKBOX_HOST" in ""|:*) BLACKBOX_HOST="blackbox-exporter.railway.internal:9115" ;; esac
case "$EXTERNAL_URL" in ""|"https://"|"http://") EXTERNAL_URL="" ;; esac

[ -n "$AUTH_PASSWORD" ] || die "AUTH_PASSWORD is unset. Prometheus has no built-in authentication, so the gateway refuses to publish an open instance."

# "a, b ,c" -> ["a", "b", "c"]
yaml_list() {
  local raw="$1" item out=""
  local IFS=','
  for item in $raw; do
    item="$(printf '%s' "$item" | tr -d '[:space:]')"
    [ -n "$item" ] || continue
    [ -z "$out" ] || out="$out, "
    out="$out\"$item\""
  done
  printf '[%s]' "$out"
}

render_prometheus_yml() {
  cat <<EOF
# Generated by entrypoint.sh on every boot. Edit the environment, not this file.
global:
  scrape_interval: ${SCRAPE_INTERVAL}
  scrape_timeout: ${SCRAPE_TIMEOUT}
  evaluation_interval: ${SCRAPE_INTERVAL}
  external_labels:
    monitor: railway

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["${ALERTMANAGER_HOST}"]

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:${PROMETHEUS_PORT}"]

  - job_name: alertmanager
    static_configs:
      - targets: ["${ALERTMANAGER_HOST}"]

  - job_name: blackbox_exporter
    static_configs:
      - targets: ["${BLACKBOX_HOST}"]
EOF

  if [ -n "$SCRAPE_TARGETS" ]; then
    cat <<EOF

  - job_name: railway_services
    metrics_path: ${METRICS_PATH}
    static_configs:
      - targets: $(yaml_list "$SCRAPE_TARGETS")
EOF
  fi

  if [ -n "$PROBE_TARGETS" ]; then
    cat <<EOF

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [${PROBE_MODULE}]
    static_configs:
      - targets: $(yaml_list "$PROBE_TARGETS")
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ${BLACKBOX_HOST}
EOF
  fi
}

render_caddyfile() {
  local hash="$1"
  cat <<EOF
{
	admin off
	auto_https off
	servers {
		trusted_proxies static 100.64.0.0/10 fd00::/8 152.233.0.0/17
	}
}

:${PORT} {
	# Anonymous, so Railway's health prober reaches it, and a real dependency check:
	# it is Prometheus' own readiness endpoint, not a static 200 from the gateway.
	handle /healthz {
		rewrite * /-/ready
		reverse_proxy 127.0.0.1:${PROMETHEUS_PORT}
	}

	handle {
		basic_auth {
			${AUTH_USERNAME} ${hash}
		}
		reverse_proxy 127.0.0.1:${PROMETHEUS_PORT}
	}
}
EOF
}

log "alertmanager: ${ALERTMANAGER_HOST}"
log "blackbox:     ${BLACKBOX_HOST}"
log "external url: ${EXTERNAL_URL:-<none>}"
log "retention:    ${RETENTION_TIME} / ${RETENTION_SIZE}"

render_prometheus_yml > /etc/prometheus/prometheus.yml
AUTH_HASH="$(caddy hash-password --plaintext "$AUTH_PASSWORD")"
[ -n "$AUTH_HASH" ] || die "caddy hash-password produced an empty hash"
render_caddyfile "$AUTH_HASH" > /etc/caddy/Caddyfile

/bin/promtool check config /etc/prometheus/prometheus.yml
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile

mkdir -p "$DATA_DIR"
chown -R prometheus:prometheus "$DATA_DIR" /etc/prometheus /etc/caddy /var/lib/caddy
chown prometheus:prometheus "$(dirname "$DATA_DIR")" 2>/dev/null || true

PROM_ARGS=(
  --config.file=/etc/prometheus/prometheus.yml
  --storage.tsdb.path="$DATA_DIR"
  --storage.tsdb.retention.time="$RETENTION_TIME"
  --storage.tsdb.retention.size="$RETENTION_SIZE"
  --web.listen-address="[::]:${PROMETHEUS_PORT}"
  --web.enable-lifecycle
)
[ -z "$EXTERNAL_URL" ] || PROM_ARGS+=(--web.external-url="$EXTERNAL_URL")

su-exec prometheus:prometheus /bin/prometheus "${PROM_ARGS[@]}" &
PROM_PID=$!
su-exec prometheus:prometheus caddy run --config /etc/caddy/Caddyfile --adapter caddyfile &
CADDY_PID=$!

shutdown() { kill -TERM "$PROM_PID" "$CADDY_PID" 2>/dev/null || true; }
trap shutdown TERM INT

# Either process exiting must take the container down, or a dead Prometheus hides
# behind a live gateway until someone opens the UI.
wait -n || true
log "a supervised process exited; shutting down"
shutdown
wait || true
exit 1
